basePath: /api/v0/
definitions:
  api.Error:
    properties:
      error:
        type: string
    type: object
  config.Config:
    properties:
      declinedPeers:
        additionalProperties:
          $ref: '#/definitions/config.DeclinedPeer'
        type: object
      httpListenAddress:
        type: string
      knownPeers:
        additionalProperties:
          $ref: '#/definitions/config.KnownPeer'
        type: object
      loggerLevel:
        type: string
      p2pNode:
        $ref: '#/definitions/config.P2pNodeConfig'
      version:
        type: string
      vpn:
        $ref: '#/definitions/config.VPNConfig'
    type: object
  config.DeclinedPeer:
    properties:
      createdAt:
        description: Time of adding to config (decline invitation/remove from KnownPeers)
        type: string
      displayName:
        type: string
      peerId:
        description: Hex-encoded multihash representing a peer ID
        type: string
    type: object
  config.KnownPeer:
    properties:
      alias:
        description: User provided name
        type: string
      confirmed:
        description: Has remote peer confirmed our invitation
        type: boolean
      createdAt:
        description: Time of adding to config (accept/invite)
        type: string
      declined:
        description: Has remote peer declined our invitation
        type: boolean
      domainName:
        description: DomainName without zone suffix (.awl)
        type: string
      ipAddr:
        description: IPAddr used for forwarding
        type: string
      lastSeen:
        description: Time of last connection
        type: string
      name:
        description: Peer provided name
        type: string
      peerId:
        description: Hex-encoded multihash representing a peer ID
        type: string
    type: object
  config.P2pNodeConfig:
    properties:
      bootstrapPeers:
        items:
          type: string
        type: array
      identity:
        type: string
      listenAddresses:
        items:
          type: string
        type: array
      name:
        type: string
      peerId:
        description: Hex-encoded multihash representing a peer ID, calculated from
          Identity
        type: string
      reconnectionIntervalSec:
        type: integer
    type: object
  config.VPNConfig:
    properties:
      interfaceName:
        type: string
      ipNet:
        type: string
    type: object
  entity.AuthRequest:
    properties:
      name:
        type: string
      peerID:
        type: string
    type: object
  entity.BandwidthDebugInfo:
    properties:
      byProtocol:
        additionalProperties:
          $ref: '#/definitions/entity.BandwidthInfo'
        type: object
      total:
        $ref: '#/definitions/entity.BandwidthInfo'
    type: object
  entity.BandwidthInfo:
    properties:
      rateIn:
        type: string
      rateOut:
        type: string
      totalIn:
        type: string
      totalOut:
        type: string
    type: object
  entity.BootstrapPeerDebugInfo:
    properties:
      connections:
        items:
          type: string
        type: array
      error:
        type: string
    type: object
  entity.ConnectionInfo:
    properties:
      address:
        type: string
      multiaddr:
        type: string
      protocol:
        type: string
      relayPeerID:
        type: string
      throughRelay:
        type: boolean
    type: object
  entity.ConnectionsDebugInfo:
    properties:
      connectedPeersCount:
        type: integer
      lastTrimAgo:
        type: string
      openConnectionsCount:
        type: integer
      openStreamsCount:
        type: integer
      totalStreamsInbound:
        type: integer
      totalStreamsOutbound:
        type: integer
    type: object
  entity.DhtDebugInfo:
    properties:
      bootstrapPeers:
        additionalProperties:
          $ref: '#/definitions/entity.BootstrapPeerDebugInfo'
        type: object
      listenAddress:
        items:
          type: string
        type: array
      observedAddrs:
        items:
          type: string
        type: array
      peersWithAddrsCount:
        type: integer
      reachability:
        enum:
          - Unknown
          - Public
          - Private
        type: string
      routingTableSize:
        type: integer
    type: object
  entity.FriendRequest:
    properties:
      alias:
        type: string
      peerID:
        type: string
    required:
      - peerID
    type: object
  entity.FriendRequestReply:
    properties:
      alias:
        type: string
      decline:
        type: boolean
      peerID:
        type: string
    required:
      - peerID
    type: object
  entity.GeneralDebugInfo:
    properties:
      uptime:
        type: string
    type: object
  entity.KnownPeersResponse:
    properties:
      confirmed:
        type: boolean
      connected:
        type: boolean
      connections:
        items:
          $ref: '#/definitions/entity.ConnectionInfo'
        type: array
      declined:
        type: boolean
      domainName:
        type: string
      ipAddr:
        type: string
      lastSeen:
        type: string
      name:
        type: string
      networkStats:
        $ref: '#/definitions/metrics.Stats'
      peerID:
        type: string
      version:
        type: string
    type: object
  entity.P2pDebugInfo:
    properties:
      bandwidth:
        $ref: '#/definitions/entity.BandwidthDebugInfo'
      connections:
        $ref: '#/definitions/entity.ConnectionsDebugInfo'
      dht:
        $ref: '#/definitions/entity.DhtDebugInfo'
      general:
        $ref: '#/definitions/entity.GeneralDebugInfo'
    type: object
  entity.PeerIDRequest:
    properties:
      peerID:
        type: string
    required:
      - peerID
    type: object
  entity.PeerInfo:
    properties:
      awlDNSAddress:
        type: string
      connectedBootstrapPeers:
        type: integer
      isAwlDNSSetAsSystem:
        type: boolean
      name:
        type: string
      networkStats:
        $ref: '#/definitions/metrics.Stats'
      peerID:
        type: string
      reachability:
        enum:
          - Unknown
          - Public
          - Private
        type: string
      serverVersion:
        type: string
      totalBootstrapPeers:
        type: integer
      uptime:
        type: integer
    type: object
  entity.UpdateMySettingsRequest:
    properties:
      name:
        type: string
    type: object
  entity.UpdatePeerSettingsRequest:
    properties:
      alias:
        type: string
      domainName:
        type: string
      peerID:
        type: string
    required:
      - peerID
    type: object
  metrics.Stats:
    properties:
      rateIn:
        type: number
      rateOut:
        type: number
      totalIn:
        type: integer
      totalOut:
        type: integer
    type: object
host: localhost:8639
info:
  contact: { }
  description: Anywherelan API
  title: Anywherelan API
  version: "0.1"
paths:
  /debug/log:
    get:
      consumes:
      - application/json
      produces:
        - text/plain
      responses:
        "200":
          description: log text
          schema:
            type: string
      summary: Get logs
      tags:
      - Debug
  /debug/p2p_info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.P2pDebugInfo'
      summary: Get p2p debug info
      tags:
      - Debug
  /peers/accept_peer:
    post:
      consumes:
      - application/json
      parameters:
      - description: Params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.FriendRequestReply'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Accept new peer's invitation
      tags:
      - Peers
  /peers/auth_requests:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.AuthRequest'
            type: array
      summary: Get ingoing auth requests
      tags:
      - Peers
  /peers/get_known:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.KnownPeersResponse'
            type: array
      summary: Get known peers info
      tags:
      - Peers
  /peers/get_known_peer_settings:
    post:
      consumes:
        - application/json
      parameters:
        - description: Params
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/entity.PeerIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.KnownPeer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
      summary: Get known peer settings
      tags:
      - Peers
  /peers/invite_peer:
    post:
      consumes:
      - application/json
      parameters:
      - description: Params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.FriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
      summary: Invite new peer
      tags:
        - Peers
  /peers/remove:
    post:
      consumes:
        - application/json
      parameters:
        - description: Params
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/entity.PeerIDRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
      summary: Remove known peer
      tags:
        - Peers
  /peers/update_settings:
    post:
      consumes:
        - application/json
      parameters:
        - description: Params
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/entity.UpdatePeerSettingsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
      summary: Update peer settings
      tags:
        - Peers
  /settings/export_server_config:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Config'
      summary: Export server configuration
      tags:
        - Settings
  /settings/peer_info:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PeerInfo'
      summary: Get my peer info
      tags:
      - Settings
  /settings/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: Params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateMySettingsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update my peer info
      tags:
      - Settings
swagger: "2.0"
