name: Manual build release

on:
  workflow_dispatch:
    inputs:
      awl_ref:
        description: 'The branch, tag or SHA of awl repository'
        required: true
        default: 'master'
      awl_flutter_ref:
        description: 'The branch, tag or SHA of awl-flutter repository'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout awl code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # also fetch tags for 'git describe'
          ref: ${{ github.event.inputs.awl_ref }}
          path: 'awl'
      - name: Checkout awl-flutter code
        uses: actions/checkout@v2
        with:
          repository: 'anywherelan/awl-flutter'
          ref: ${{ github.event.inputs.awl_flutter_ref }}
          path: 'awl-flutter'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: 'stable'
      - run: flutter --version

      - name: Build
        run: |
          cd awl
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get -d golang.org/x/mobile/cmd/gomobile
          gomobile init
          go mod tidy
          cd cmd/awl-tray && go mod tidy && cd ../..
          ./build.sh docker-images
          ./build.sh release
          echo "ls build"
          ls -la build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: awl-release-build
          path: awl/build/*
          if-no-files-found: error
