name: Test
on: [ push, pull_request ]
jobs:
  test:
    # run job on all pushes OR external PR, not both
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Create stub static/
        run: mkdir static && touch static/index.html
      - name: Create stub wintun.dll
        run: touch embeds/wintun.dll
        if: matrix.os == 'windows-latest'
      - name: gofmt && go mod tidy
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          cd cmd/awl-tray && go mod tidy && cd ../..
          test -z "$(gofmt -d .)" || (gofmt -d . && false)
          test -z "$(git status --porcelain)" || (git status; git diff && false)
      - name: Test
        run: go test -count=1 ./...
      - name: Test with -race
        run: go test -race -count=1 ./...
      - name: Build cmd/awl
        run: go build github.com/anywherelan/awl/cmd/awl
